### PR TITLE
[LS] Bump cadence to v0.40.0

### PR DESCRIPTION
**Pull request by jribbink**

### CODE REVIEW

**Comment by sideninja** [comment]
hmm I wonder why this CI doesn't finish, @jribbink are you able to run it locally?

**Comment by sideninja** [comment]
Looks there's an issue with test:
```
    expect(received).toHaveLength(expected)

    Expected length: 1
    Received length: 0
    Received array:  []

      237 | 
      238 |       expect(notification.uri).toEqual(uri)
    > 239 |       expect(notification.diagnostics).toHaveLength(errors.length)
          |                                        ^
      240 |       notification.diagnostics.forEach(
      241 |         (diagnostic, i) => expect(diagnostic.message).toEqual(errors[i])
      242 |       )

      at index.test.ts:239:40
```

**Comment by SupunS** [comment]
I think we need to update all the downstream dependencies (go-sdk, flow-go, lint, etc.) to cadence `v0.40.0` before updating the LS.

I guess @turbolent is already on to it.

**Comment by sideninja** [comment]
Not sure if this is related since if updated the go-sdk would use the later version, but this dep management can be messy so worth also making sure we update go-sdk yeah @jribbink

**Comment by turbolent** [comment]
I fixed the CI issue a while ago in #158, please review

**Comment by jribbink** [comment]
Just working on updating the other dependencies to fix the tests...

**Comment by jribbink** [comment]
Blocked by https://github.com/onflow/cadence-tools/pull/184

**Comment by turbolent** [comment]
Discussed the crypto blocker with @tarakby. Created an SDK release without the crypto library switch and update flow-go, please review: https://github.com/onflow/flow-go/pull/4603

**Comment by turbolent** [comment]
Replaced by #189

**Pull request closed without merging**
