### PR TITLE
Move language-server to the cadence-tools repo

### PR DESCRIPTION
**Pull request by SupunS**
Preserves commit history.
______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence-lint/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by turbolent — APPROVED** [review]
👋

**Comment by turbolent** [comment]
Just realized: We also need to move `npm-packages/cadence-language-server` over. Maybe in a separate PR?

**Review by sideninja — COMMENTED** [review]
Should we keep the root `languageserver` folder?

**Comment by sideninja** [comment]
> Just realized: We also need to move `npm-packages/cadence-language-server` over. Maybe in a separate PR?

+1

**Review by dsainati1 — APPROVED** [review]

**Comment by SupunS** [comment]
> Just realized: We also need to move npm-packages/cadence-language-server over. Maybe in a separate PR?

Yeh, need to move np-packages for both language-server and the doc gen. Will do that in a separate PR.

**Comment by SupunS** [comment]
> Should we keep the root languageserver folder?

Need to keep the `languageserver` at the root level because there is a separate module for each tool. The current structure is:
```
|_languageserver
|    |_ ...
|
|_lint
|    |_...
|
|_test
     |_...

```

**Pull request merged**
