### PR TITLE
[LS] Bump `onflow/cadence` dependency to `v0.42.0`

### PR DESCRIPTION
**Pull request by m-Peter**
Depends on: https://github.com/onflow/cadence-tools/pull/210

## Description

Also adds a default implementation for the `ContractUpdateRecorded` method.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence-lint/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by turbolent — APPROVED** [review]
Thank you!

**Review by SupunS — COMMENTED** [review]
Thank you for updating the dependency versions 🙏 

However, we might need to update Cadence version for all other dependencies of LS (i.e: transitive dependencies). For e.g: LS depends on flowkit, lint, flow-go-sdk, etc, which again depends on an older version of Cadence. Having two versions of Cadence in the dependency tree could cause some unexpected behaviors for some of these modules. i.e: They could pick the newer version of Cadence for which that module is not tested yet.
(Unfortunately, that's a problem with Go dependency resolution)

**Comment by m-Peter** [comment]
That's a good point :+1: 
Regarding `lint`, there's already a PR open: https://github.com/onflow/cadence-tools/pull/219. But I think the `flow-go-sdk` latest version is not updated to `cadence@v0.42.0`.
I have opened another PR for updating `flow-emulator` to `cadence@v0.42.0` and latest `flow-go`: https://github.com/onflow/flow-emulator/pull/483
I am in need of these updates in order to merge https://github.com/onflow/flow-cli/pull/1227 :sweat_smile: :pray:
We can then release the uplift for the Cadence testing framework.
Let me know how can I help on my part, to speed up the process.

**Comment by m-Peter** [comment]
I have updated `flow-go-sdk` and `cadence-tools/lint` dependencies. I think `flowkit` is a circular dependency, so it will have to be updated last, after this PR is merged.

**Review by turbolent — APPROVED** [review]

**Review by SupunS — APPROVED** [review]

**Pull request merged**
