### PR TITLE
[test] Remove `FUSD` contract referrences

### PR DESCRIPTION
**Pull request by m-Peter**
## Description

The `FUSD` contract was removed from Flow Emulator, so I have updated the `flow-emulator` and `flow-go` versions and fixed the relevant breaking changes that occurred.
______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence-lint/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by janezpodhostnik — APPROVED** [review]

**Comment by m-Peter** [comment]
@sideninja After this is merged, we'll need a release for `cadence-tools/test`, and I will follow up with a PR on `flow-cli` to bump the version.

**Review by sideninja — APPROVED** [review]
Thank you

**Comment by sideninja** [comment]
@m-Peter should we also release LS?

**Comment by m-Peter** [comment]
I am not sure if there are unreleased changes there, but if there are, it's a good time to release them both :pray:

**Comment by sideninja** [comment]
I meant because this PR changes LS go deps too

**Comment by m-Peter** [comment]
Oh, yes, I totally forgot about this :sweat_smile:

**Comment by m-Peter** [comment]
The build would fail: https://github.com/onflow/cadence-tools/actions/runs/5623624068/job/15238707883, that's why I had to update the deps in the entire repo.

**Pull request merged**
