### PR TITLE
[LS] Provide code actions for suggested fixes of sema errors

### LINKED ISSUE #159: [LS] Propose adding missing argument labels in function invocation
### Issue To Be Solved

A function invocation might be missing the argument labels required by the function definition.

### (Optional): Suggest A Solution

Add a quick fix to add the required argument labels.

### PR DESCRIPTION
**Pull request by turbolent**
Closes #159

## Description

Just like providing code actions for suggested fixes of analysis diagnostics, also provide them for sema errors.

https://github.com/onflow/cadence/pull/2619 demonstrates this for argument labels, it provides the following suggested fixes / code actions:
- Add missing argument label that is required
- Replace incorrect argument label
- Remove argument label where not allowed

https://github.com/onflow/cadence-tools/assets/51661/4e178fea-b93d-4c71-855b-f87d32f124d2

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence-lint/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by sideninja** [comment]
@turbolent looks like there's an issue with TextEdit type

**Comment by turbolent** [comment]
As noted in the description, this PR depends on a Cadence update (v0.40.0), which is in progress

**Comment by sideninja** [comment]
> As noted in the description, this PR depends on a Cadence update (v0.40.0), which is in progress

I thought because it was merged it was released. Now v0.40.0 is available right?

**Comment by turbolent** [comment]
No review in over a month, merging as-is

**Pull request merged**
