### PR TITLE
[LS] Restore WASM build

### PR DESCRIPTION
**Pull request by jribbink**
Closes #243 

## Description

Restores the WASM build using the new build tag from `onflow/crypto`

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence-lint/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by turbolent — APPROVED** [review]
Nice!

**Comment by jribbink** [comment]
Hmmm looks like it's building, but failing tests.  Will investigate...

**Comment by turbolent** [comment]
@jribbink it's likely https://github.com/golang/go/issues/61982#issuecomment-1676067464

**Comment by turbolent** [comment]
We probably should:
- "revert" the removal of specifying a Go version, and pin a fixed version of Go https://github.com/onflow/cadence-tools/commit/eb79d1d14372434b44e382d20bbca9f5549f329c (the update of the action version is fine)
- Update https://github.com/onflow/cadence-tools/blob/fe1e785553a19edb6cb513948903655feb4d4227/npm-packages/cadence-docgen/src/go.js to that pinned version's `wasm_exec.js`

**Review by turbolent — APPROVED** [review]
👏

**Pull request merged**
