### PR TITLE
[LS] Update and publish NPM package 0.40.0

### PR DESCRIPTION
**Pull request by bthaile**
Updating the version in package.json to 0.40.0 and publishing to NPM

### CODE REVIEW

**Comment by sideninja** [comment]
I've automated the publishing of LS to the npm. Was LS tagged? that would trigger the automatic update.

**Comment by bthaile** [comment]
I forgot that part. I didn't tag anything

**Comment by sideninja** [comment]
I will tag and it should automatically do it. Let me see. Will close this after.

**Comment by bthaile** [comment]
Is there docs that can remind me what needs to be done to release?

**Comment by jribbink** [comment]
I think merging this PR https://github.com/onflow/cadence-tools/pull/184 then making a new release will get the changes Tom needs for the playground out

**Comment by sideninja** [comment]
https://github.com/onflow/cadence-tools/pull/185
https://github.com/onflow/cadence-tools/pull/186

**Comment by sideninja** [comment]
> I think merging #184 then making a new release will get the changes Tom needs for the playground out

I see. ok

**Comment by bthaile** [comment]
geesh! notion, how about how-to release in the language server Readme.

**Pull request closed without merging**
