### PR TITLE
[LS] Fix wasm target

### PR DESCRIPTION
**Pull request by bluesign**
______

- [x] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence-lint/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by turbolent** [comment]
Thank you for fixing this! 🙏 Verified this is working as expected by running `make build` which builds both native and WASM binaries 👌 

Could you please open this in two separate PRs, one against the test framework and another one against the LS?

I also opened #244 as a follow-up to prevent regressions like this

**Comment by bluesign** [comment]
ah sure, I will separate it today.

**Comment by turbolent** [comment]
https://github.com/onflow/cadence-tools/releases/tag/test%2Fv0.14.2 is released now.

@bluesign Could you please update the PR with just the LS changes, and replacing the go mod `replace` statement with an update to the latest `cadence-tools/test` release? Thank you!

**Comment by bluesign** [comment]
@turbolent should be ok now. Also changed PR status to ready for review.

**Review by turbolent — APPROVED** [review]
Perfect! Thanks again :pray:

**Pull request merged**
